### ISSUE TITLE
Add/Remove Panes issues

### ISSUE THREAD

**Issue by orefalo** [orefalo/svelte-splitpanes#15]
In the **Adding splitters programmatically** demo at https://orefalo.github.io/svelte-splitpanes/

Remove all splitters in the panel by clicking the remove button well beyond the number of active sub panes.

Then add the panels back

Two issues:
1. It takes several clicks to get the first panel to show -> the counter needs to be bounded
2. First panel doesn't show, the splitpane shows on the 2nd iteration, but it's closed

https://user-images.githubusercontent.com/52085/174793792-a18feb0b-a666-45ad-a293-58cb2ad20847.mov

!

**Comment by Tal500** [comment]
According to my tests, this issue happen already in an older version - 5080aea3dd77a7da7474810ab985f51d4249178b

**Comment by Tal500** [comment]
> 1. It takes several clicks to get the first panel to show -> the counter needs to be bounded

Didn't understand what you mean by this

**Comment by Tal500** [comment]
BTW: It sounds like a good idea to make the "Remove Pane" button disabled if the panes count is `0`.

**Comment by orefalo** [comment]
Correct, bounding to 0 will solve the issue.

to reproduce... say there is 3 panes.
Click REMOVE 10 times.

The expectation here that, when you click ADD, a new pane should show right away.

well it doesn't

I actually checked with the original implementation and I believe it's a non issue.

**Comment by Tal500** [comment]
> Correct, bounding to 0 will solve the issue.
> 
> to reproduce... say there is 3 panes. Click REMOVE 10 times.
> 
> The expectation here that, when you click ADD, a new pane should show right away.
> 
> well it doesn't
> 
> I actually checked with the original implementation and I believe it's a non issue.

Tested on Firefox, doesn't happen to me.
It is strange since there is an explicit condition in the `on:click` which should saves you from falling to this case

**Comment by Tal500** [comment]
Added PR

**Comment by orefalo** [comment]
Thank you fixed
