### ISSUE TITLE
Splitter Jiggler

### ISSUE THREAD

**Issue by orefalo** [orefalo/svelte-splitpanes#16]
A little video is better than a long speach -
plz be patient....

https://user-images.githubusercontent.com/52085/174794398-39c1ed9e-3e09-4986-b8fb-94f1f7969d1f.mov

**Comment by orefalo** [comment]
and while I am at it .. I do see an issue with the pointer again...

**Comment by Tal500** [comment]
In my tests, it occurs also in a much older version, in cd1182d78dd2c132b0cb4b14d05dc87faf6d3f8a .

**Comment by orefalo** [comment]
yes, I tried to find the issue the other day with no success... I might not be looking in the right place.

**Comment by Tal500** [comment]
After working on the snap thing, I'm pretty sure it is related to an issue with panes pushing in `doPushOtherPanes` function.

Might be related to [the bug I mentioned](https://github.com/orefalo/svelte-splitpanes/pull/26#issuecomment-1169738376) while working on snapping:

> I also changed the code to allow only snap to the minimum direction.
> There were a problem with the pane pushing, so I made a hack to disable it on snapping for now (should be fixed for good in the future).
> See [my changes in the code here](https://github.com/orefalo/svelte-splitpanes/commit/a74b092ad19b056e6069e6c64766ca623c387f3a#diff-09fecdf9d3beab3e46c2b4d951444190976b1a5acc07616d15b7f00836ead343).

**Comment by orefalo** [comment]
problem is fixed in master -
I am tired and will release a new npm version tomorrow.
Cheers,

**Comment by Tal500** [comment]
> problem is fixed in master - I am tired and will release a new npm version tomorrow. Cheers,

Sorry, still problematic to me in 20c2c5638666c3809138bec7c64d2ef23e6b7ebc

**Comment by orefalo** [comment]
I was really dead last night, this message should have gone to the other ticket.
