### ISSUE TITLE
Change the type of Pane `size`, `minSize` and `maxSize` to number

### ISSUE THREAD

**Issue by Tal500** [orefalo/svelte-splitpanes#17]
See title. Makes no sense to me that you put string inside of this attributes.

**Comment by Tal500** [comment]
I would like to see this improvement that the user could write `"33px"`, however I believe that even then the library should accept also integers, and in this future the percentages string should be `"25%"`  and not `"25"`). This is why in the meantime I believe it should be a number. I see no problem at the curly braces as it's standard in Svelte.

**Comment by orefalo** [comment]
Correct, in a near future it could be
"33px" -> 33 pixels
"33" or "33%" -> 33%


The issue with the number Tal is that we are introducing a breaking change **today**... and most likely **in the future** too (when we switch the type back to a string)

Besides, what is the rational with preventing quoted values in a markup language?
This is perfectly fine in HTML, and it was agreed by a whole consortium of engineers
<div flag="true" width="33">

Would you agree?

**Comment by Tal500** [comment]
First, untill this package goes to version 1.0, I think (and node.js convention too) that there should not be API guarantee.

Secondly, the precentages in string makes so much sense for me (in declarative HTML), but if you really want you can support both "33" and "33%".

About the convention, for svelte component it is very common to accept only number as properties, as far as I know. It makes sense since you can pass in properties even JS objects. See the svelte tutorial for example.

**Comment by orefalo** [comment]
Evening Tal, can I close this one.
We agreed to have the width attribute as a number. it's a %
ie. <... width={33} />
if the width is null -> it's auto-sized.


let me know, it's ez to implement.
Alright, time to sleep: good night

**Comment by Tal500** [comment]
Yes, sounds great exactly like this, no strings for now, `number` or `null` only and the meaning is in %, and if null it's auto.

Good night!

**Comment by Tal500** [comment]
I have fixed this issue in 5685fbda5baae7906a2b3d4ac68f2f1a9a2b3bd2 .

Notice that now, assuming `size != null`, you have data binding to the size! See the example of resizing by the range bar.

Notice also the following comment in the code, about an issue that remain with auto sizing:
https://github.com/orefalo/svelte-splitpanes/blob/5685fbda5baae7906a2b3d4ac68f2f1a9a2b3bd2/src/comp/ProgResize.svelte#L27-L37

**Comment by orefalo** [comment]
I believe this is a breaking change, isn't it?

**Comment by orefalo** [comment]
oh, but it was pushed some time back

**Comment by orefalo** [comment]
I just learned something I didn't know.
the parameter is number right, so you expect it to fail with something like <Pane minSize="15">

but no, it appears svelte converts the parameters correctly.
