### ISSUE TITLE
styling in the svelte REPL?

### ISSUE THREAD

**Issue by zahachtah** [orefalo/svelte-splitpanes#2]
Hi, great component, very useful for me! question: how do I need to adapt the code to do the styling in the svelte REPL?

https://svelte.dev/repl/3434f0b23d534ba4bb962ec88a3ae1e5?version=3.48.0

Many thanks!

**Comment by orefalo** [comment]
glad it helps,

a style section should suffice.

did you check the other demo link? it has  many examples which should just run with a copy paste into REPL

**Comment by zahachtah** [comment]
Thats what I did, the link above is the cut and pasted version with styled splitters, but the styling does not show up unfortunately...

**Comment by orefalo** [comment]
ok. unfortunately not the best time for me to troubleshoot. please give me 48h ty

**Comment by orefalo** [comment]
didn't try your version of the code, took one of the ones from the demo page, copy/paste

->https://svelte.dev/repl/95d67f36254c499ca9e5c69c32d7abbb?version=3.48.0

seems to work

**Comment by zahachtah** [comment]
ok, I had left a class="default-theme" in the split-and component....


thanks, all solved....

**Comment by orefalo** [comment]
good.

Indirectly related, I found that a class prop on Pane could be super useful.

Change already pushed.

Sincerely

**Comment by orefalo** [comment]
Hi, thank you for pointing issues with styling. I reworked it with a `theme` attribute and fixed the css styles.
it's now much easier to style and more consistent.  check the demos.

Sincerely
