### ISSUE TITLE
Add code QA tools to the repo

### ISSUE THREAD

**Issue by orefalo** [orefalo/svelte-splitpanes#23]
* husky
* lintstage
* commitlint
* cz-customizable
* standard-version

**Comment by Tal500** [comment]
I think about creating a github action that automatically generates the docs, when pushing to the master branch.

**Comment by orefalo** [comment]
Nice work on the docs autogen, ty

**Comment by Tal500** [comment]
> Nice work on the docs autogen, ty

Of course.
I see that the docs delivery were failed (see Github Actions).
Did you change the setting I showed to take the docs from the branch `gh-pages`(instead of `master`)?

**Comment by orefalo** [comment]
correct, forgot - it's now fixed

**Comment by Tal500** [comment]
I should also say that there is an important basic feature we currently don't actively use, `svelte-check`, that can be run (already!) by `npm run check` (The errors and the hints should be familiar, they are the ones Visual Studio Code shows all the time).
There are many hints, but two errors remained that it would be nice to fix, so we can add this check to the test workflow in Github Action:
```
c:\Src\svelte-splitpanes\src\lib\Splitpanes.svelte:348:12
Error: Argument of type 'string' is not assignable to parameter of type '"pane-add" | "pane-remove" | "pane-click" | "ready" | "resize" | "resized" | "splitter-click" | "pane-maximize"'. (ts)
        function dispatchSizeEvent(name: string) {
                dispatch(name, prepareSizeEvent());
        }


c:\Src\svelte-splitpanes\src\lib\Splitpanes.svelte:406:21
Error: Argument of type '() => number' is not assignable to parameter of type 'number'. (ts)
                                paneBefore.setSz(Math.max(100 - paneAfter.max() - sums.prevPanesSize - sumNextPanesSize(splitterIndex + 1), 0));
                                paneAfter.setSz(paneAfter.max);
                        }
```

The first error is related to the event dispatching, and the second is because you should call `paneAfter.max()`.

**Comment by Tal500** [comment]
Also I see some linting errors that needed to be fixed (`npm run lint`)

**Comment by Tal500** [comment]
After fixing these issues, we can use husky to add hooks to git, as you can see [in the husky guide](https://typicode.github.io/husky/#/?id=create-a-hook).

However, I wouldn't recommend on running the playwright tests in hooks, they are heavy and intentionally they are in optional deps.

**Comment by orefalo** [comment]
closing - thank you Tal ;-)

**Comment by orefalo** [comment]
paneAfter.max => this is most likely the issue with the jitter sizing.

**Comment by Tal500** [comment]
> closing - thank you Tal ;-)

Why to close? There is still a huge work to be done here, as I mentioned. I suggest to reopen.

Additional note: Need to implement auto versioning. `standard-version` is deprecated, and [has recommended to use](https://www.npmjs.com/package/standard-version) the project [release-please](https://github.com/googleapis/release-please) instead:

> standard-version is deprecated. If you're a GitHub user, I recommend [release-please](https://github.com/googleapis/release-please) as an alternative. I encourage folks to fork this repository and, if a fork gets popular, I will link to it in this README.

**Comment by orefalo** [comment]
I am working on it right now

**Comment by orefalo** [comment]
yes, you may skip scoping for now

**Comment by Tal500** [comment]
Update: d81e5e5be7576e7e875b576615e24e54262a95b6 do automatic lint&svelte-check checks on GitHub Actions.

**Comment by orefalo** [comment]
nice, thank you.
well I am learning a few things in github actions myself ;-/

shall the ticket be closed?

**Comment by Tal500** [comment]
> nice, thank you. well I am learning a few things in github actions myself ;-/
> 
> shall the ticket be closed?

Yes!
We need to create a ticket of "exploring the usage of release-please" bot. (he's up now, need to see what will he do)
