### ISSUE TITLE
resize vs resized events

### ISSUE THREAD

**Issue by orefalo** [orefalo/svelte-splitpanes#27]
@Tal500 question....

Why do we have resize and resized events?
What is the difference?

Shouldn't it be one?

**Comment by Tal500** [comment]
As far as I see:
* `resize` is progressive, while dragging occurs
* `resized` is when the user leave the mouse/touch from the splitter, and inform the user the resize operation were done and finished.

**Comment by orefalo** [comment]
yep stupid question sorry, found the code.
will update the README
