### ISSUE TITLE
[Setting Change] Allow all workflows to run during PR

### ISSUE THREAD

**Issue by Tal500** [orefalo/svelte-splitpanes#28]
When a non-collaborator publishes PR, GitHub requires by default to approve running the workflow for his PRs.
I suggest changing this strict security to a more lenient by the project settings/actions/general as [described here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#controlling-changes-from-forks-to-workflows-in-public-repositories). Specifically, I think we should pick the first bullet, the least restrictive, since the workflow that is activated by PR are secured:
![תמונה](https://user-images.githubusercontent.com/1467072/176019098-f3e60591-4861-4d7a-957c-0295486cee45.png)

**Comment by orefalo** [comment]
Agreed, just changed the setting.
