### ISSUE TITLE
github action

### ISSUE THREAD

**Issue by orefalo** [orefalo/svelte-splitpanes#29]
Morning @Tal500 ,

the action fails with 
```
[tests](https://github.com/orefalo/svelte-splitpanes/runs/7086398111?check_suite_focus=true#logs)
failed 2 minutes ago in 13s
Search logs
2s
1s
4s
5s
Run bahmutov/npm-install@v[1](https://github.com/orefalo/svelte-splitpanes/runs/7086398111?check_suite_focus=true#step:4:1).4.5
running npm-install GitHub Action
trying to restore cached NPM modules
Received 2169[3](https://github.com/orefalo/svelte-splitpanes/runs/7086398111?check_suite_focus=true#step:4:4)288[4](https://github.com/orefalo/svelte-splitpanes/runs/7086398111?check_suite_focus=true#step:4:5) of 216932884 (100.0%), 19[5](https://github.com/orefalo/svelte-splitpanes/runs/7086398111?check_suite_focus=true#step:4:6).7 MBs/sec
Cache Size: ~207 MB (21[6](https://github.com/orefalo/svelte-splitpanes/runs/7086398111?check_suite_focus=true#step:4:7)932884 B)
/usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/9322d40a-9bd6-4622-9d52-4[7](https://github.com/orefalo/svelte-splitpanes/runs/7086398111?check_suite_focus=true#step:4:8)d62ff2b534/cache.tzst -P -C /home/runner/work/svelte-splitpanes/svelte-splitpanes
npm cache hit yarn-linux-x64-363[8](https://github.com/orefalo/svelte-splitpanes/runs/7086398111?check_suite_focus=true#step:4:9)[9](https://github.com/orefalo/svelte-splitpanes/runs/7086398111?check_suite_focus=true#step:4:10)9fee4314ee5ad7ab93cb474dbe7d5725f9e50acd68d577ea2c160ea4e2119ddf3ec0db42aaa0efdc02d7ce374bbc0afb464ce99201cf79f2cb2b0b8130b
installing NPM dependencies using Yarn
yarn at "/usr/local/bin/yarn"
/usr/local/bin/yarn --frozen-lockfile
yarn install v1.22.19
[1/4] Resolving packages...
error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: The process '/usr/local/bin/yarn' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/bahmutov/npm-install/v1.4.5/dist/index.js:962:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/bahmutov/npm-install/v1.4.5/dist/index.js:945:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/bahmutov/npm-install/v1.4.5/dist/index.js:839:27)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:[10](https://github.com/orefalo/svelte-splitpanes/runs/7086398111?check_suite_focus=true#step:4:11)22:[16](https://github.com/orefalo/svelte-splitpanes/runs/7086398111?check_suite_focus=true#step:4:17))
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
Error: The process '/usr/local/bin/yarn' failed with exit code 1
```

I did update a `yarn` which did change the lockfile, then pushed the change.
however, this is still breaking.

any idea?

**Comment by Tal500** [comment]
Hello! Saw it yesterday, and my wife told me I need to sleep so I didn't manage to fix this. Didn't want to make you unable to sleep.
It happened first on the commit you had updated sveltekit. When I downloaded the changes yesterday to my machine(after fixing yarn locally), another error happen, because of the convension of `svelte` and `sveltekit` in app.html. 

In the last actions I still see the issue with the yarn file though.

I suggest you'd do fresh "yarn install", and maybe even delete the "node_modules" directory before if really need to.
BTW: You might already just move to PNPM, simply by removing the lock file and do "pnpm install"

**Comment by Tal500** [comment]
I see the issue with the actions now
You didn't commit `yarn.lock` but rather some [yarn error file](https://github.com/orefalo/svelte-splitpanes/commit/697ffed9f2e9325f0de8d9018f384cba12c1198b#diff-a2b6efbfdcf1ef38207392bbe0d2316d07f49cb87184999c894e9535e2eb65cc)

**Comment by orefalo** [comment]
;-)

I think I am ready to move to pnpm. 

But.. I believe it's an issue with caching on github.
  Maybe using pnpm in the action will solve it all.

**Comment by orefalo** [comment]
really?
I find it error prone

**Comment by Tal500** [comment]
> I see the issue with the actions now You didn't commit `yarn.lock` but rather some [yarn error file](https://github.com/orefalo/svelte-splitpanes/commit/697ffed9f2e9325f0de8d9018f384cba12c1198b#diff-a2b6efbfdcf1ef38207392bbe0d2316d07f49cb87184999c894e9535e2eb65cc)

Were you commenting on this?
You have commuted the wrong yarn file

**Comment by Tal500** [comment]
I suggest you to commit first the yarn lock, and then if actions work, move to pnpm

**Comment by orefalo** [comment]
closed - my mistake yarn.lock was out of sync
I will make that mistake again...
