### ISSUE TITLE
Need to toggle a special class for the "active" splitter

### ISSUE THREAD

**Issue by Tal500** [orefalo/svelte-splitpanes#34]
And then I was shocked, I didn't notice this before.

It make sense to style the currently "dragged" splitter differently, but right now there is not an easy way for this.

Should be easy, just to toggle some class name on the "splitter" `div` element, which reports if it's active or not.
What should be the name? (to avoid collision)

**Comment by orefalo** [comment]
active

**Comment by Tal500** [comment]
> active

Should it have some prefix like __splitpanes__splitter__active and so?

**Comment by orefalo** [comment]
it must, because those classes are not scrambled and end up in the global css space.

call it 'splitpanes__active'

**Comment by orefalo** [comment]
in fact if you search for '.splitpanes__' you will find all the global styles

**Comment by orefalo** [comment]
so far I managed to liven without setting an '*active' class.  special styles trigger on hover.

**Comment by Tal500** [comment]
fixed in 83c056681484a7c5054b83b37980d36c7f331c28

This commit also allowed me to fix a problem in the examples, see 2de44afbe816dd086aa6591e0d785984b2a2e937
