### ISSUE TITLE
Native style snap

### ISSUE THREAD

**Issue by joakim** [orefalo/svelte-splitpanes#37]
First of all, thanks for porting this to Svelte! It's really great, my only quibble is the snapping mechanism. It's not as good as it could be. I want to make app UIs that feel as solid as native apps, and it's worth looking at how they do snapping.

Two good examples are VS Code and Apple's Finder. The sidebar's splitter has a (fixed) "minSize". If you keep resizing below that size, you reach a threshold at about half the width of the pane, causing it to collapse (or expand again).

I tried playing around with `snapSize` and `minSize`, but apparently the snap mechanism of `svelte-splitpanes` is the opposite of VS Code and Finder. Instead of snapping to `0` when below a certain threshold, it snaps to `minSize` when below `snapSize`. To me, at least, that's not very intuitive. It feels more flimsy than professional UIs.

To fully replicate VS Code style splitpanes, fixed sizes would also have to be supported (discussed in #33). I think it's not just a nice to have. A good use case is exactly that of UIs where the sidebar should be collapsible, while still having a fixed "minSize" that keeps the sidebar visible until it snaps.

**Comment by joakim** [comment]
To be somewhat constructive, how about changing the behavior so that if `snapSize < minSize`…

    <Pane snapSize={5} minSize={10} maxSize={80}>

… it snaps to `0` _from_ `5`, while keeping the pane at `10` until then?

That's the behaviour I expected, and would be close enough to native UIs for me.

**Comment by Tal500** [comment]
Hi @joakim !
There were a lot of debate about features and consistency, discussed within a detailed conversation in #26.

In short, this is the idea:
Every existing pane have a minimal size of minSize, **meaning it never can be less**(unless you remove it completely). The same apply with maxSize, but this is irrelevant for the discussion now(in purpose we decided to make this size irrelevant with respect to snapSize, see the discussion there).

The snap size determines what is the gap between minSize and the current size, such that within this gap, the pane will be snapped. I.e. the snap behaviour is: Snap the pane to the minimal size, if the current size of the pane is less than `minSize + snapSize`.

So now we know the definitions, I believe that your idea can be implemented simply by doing both:
* Set minSize to be 0
* Set snapSize to the amount you wish

Meaning, that within the gap of less than `0 + snapSize`(=`snapSize`), the pane will snap to the minimal size (equals 0).

What do you think?

**Comment by joakim** [comment]
Wish I had seen that issue before :) I understand the rationale behind the snap behaviour now. It does make sense for collapsing adjacent panes of the same type.

Unfortunately, it's not enough to replicate Apple/Microsoft's sidebar snapping. I tried `minSize={0} snapSize={10}`, which does work, but it's what I'd call flimsy compared to the "benchmark". It's a question of UX. There's a reason Apple and Microsoft's UI designers chose that behaviour. Squishing your sidebar content until it suddenly disappears just feels wrong, almost like a bug.

Maybe adding another size property could make it work with the existing behaviour? `stickSize`?

    <Pane minSize={0} snapSize={5} stickSize={10} maxSize={80}>

When resizing from larger to smaller, you first hit `stickSize`, making the pane stick to that size (until it snaps). Later you hit `snapSize`, causing the pane to snap to `minSize`. That would work just like native sidebars, I think, without breaking existing behaviour. What do you think?

**Comment by Tal500** [comment]
> Maybe adding another size property could make it work with the existing behaviour? `stickSize`?
> 
> ```
> <Pane minSize={0} snapSize={5} stickSize={10} maxSize={80}>
> ```
> 
> When resizing from larger to smaller, you first hit `stickSize`, making the pane stick to that size (until it snaps). Later you hit `snapSize`, causing the pane to snap to `minSize`. That would work just like native sidebars, I think, without breaking existing behaviour. What do you think?

Checked again in VS Code and I see your point. This looks overall good to me.
What do you think @orefalo ?

Anyway, we are currently not available to work too much on this project, but I believe we'd like to see PR (including explanation in the docs).

**Comment by Tal500** [comment]
I also wants to mention that if PR is too hard, this can be implemented in the user land by subscribing to pane size events.

**Comment by joakim** [comment]
I might be able to have a go at a PR eventually, but I can't prioritise it at the moment.

> I also want to mention that if PR is too hard, this can be implemented in the user land by subscribing to pane size events.

Oh, it can? I haven't looked into events, I assumed I couldn't affect any behaviours that way. I'll have a closer look then!

**Comment by joakim** [comment]
You were right, I could made it work in userland. With not too much of a hack either.

I use `theme` to enforce `min-width` in CSS when the sidebar is open. I also calculate the "breakpoint" on window resize, to half the minimum width of the sidebar, converted to a percentage. Otherwise, the breakpoint would move when the window is resized.

```html
<script>
  const sidebarMinWidth = 200 // in px
  let windowWidth // in px

  // Calculate "breakpoint" on window resize (half the width of the sidebar,
  // converted to a percentage of the window's inner width)
  let sidebarSnap = 0
  $: sidebarSnap = ((sidebarMinWidth / windowWidth) * 100) / 2

  let sidebarState = 'open'

  const onSidebarResize = (event) => {
    const { size, snap } = event.detail[0]
    if (sidebarState === 'open' && size < snap) {
      sidebarState = 'closed'
    }
    else if (sidebarState === 'closed' && size > snap) {
      sidebarState = 'open'
    }
  }
</script>

<svelte:window bind:innerWidth />

<Splitpanes theme={sidebarState} on:resize={onSidebarResize}>
  <Pane size={0} minSize={0} maxSize={80} snapSize={sidebarSnap} class="sidebar"></Pane>
  <Pane></Pane>
</Splitpanes>

<style global lang="scss">
  .splitpanes.open .sidebar {
    min-width: 200px;
  }
</style>
```

Demo (with doubleclicking the splitter at the end):

https://user-images.githubusercontent.com/34790/194891000-67358a30-6c57-44df-8afa-5669a3116386.mp4

See it looped here: https://imgur.com/a/8FT5qxJ

**Comment by Tal500** [comment]
> You were right, I could made it work in userland. With not too much of a hack either.
> 
> I use `theme` to enforce `min-width` in CSS when the sidebar is open. I also calculate the "breakpoint" on window resize, to half the minimum width of the sidebar, converted to a percentage. Otherwise, the breakpoint would move when the window is resized.
> 
> ```
> <script>
>   const sidebarMinWidth = 200 // in px
>   let windowWidth // in px
> 
>   // Calculate "breakpoint" on window resize (half the width of the sidebar,
>   // converted to a percentage of the window's inner width)
>   let sidebarSnap = 0
>   $: sidebarSnap = ((sidebarMinWidth / windowWidth) * 100) / 2
> 
>   let sidebarState = 'open'
> 
>   const onSidebarResize = (event) => {
>     const { size, snap } = event.detail[0]
>     if (sidebarState === 'open' && size < snap) {
>       sidebarState = 'closed'
>     }
>     else if (sidebarState === 'closed' && size > snap) {
>       sidebarState = 'open'
>     }
>   }
> </script>
> 
> <svelte:window bind:innerWidth={windowWidth} />
> 
> <Splitpanes theme={sidebarState} on:resize={onSidebarResize}>
>   <Pane size={0} minSize={0} maxSize={80} snapSize={sidebarSnap} class="sidebar"></Pane>
>   <Pane></Pane>
> </Splitpanes>
> 
> <style global lang="scss">
>   .splitpanes.open .sidebar {
>     min-width: 200px;
>   }
> </style>
> ```
> 
> Demo (with doubleclicking the splitter at the end):
> 9REPHpg.mp4
> 

Great! Glad to see.

I would like to see PR that do this with `stickSize`(with measurements in percentages) however. See the changes of PR #26 for referencing the relevant lines of code.

Assuming this will be created and merged (and solves this issue), your code will be much more simplified, and will only contain the conversion from percentages to pixels on the client side.


> See it looped here: https://imgur.com/a/8FT5qxJ
I need to have your frontend designing skills... I only feel comfortable at designing code logic and edge cases.

**Comment by joakim** [comment]
We each have our strengths and interests :)

Looks like I won't have time to work on a PR any time soon, unfortunately. The workaround works for me.

**Comment by orefalo** [comment]
Thank you for the feedback @joakim 
Closing the ticket as workaround proved useful
