### ISSUE TITLE
[docs] link this project to Vercel

### ISSUE THREAD

**Issue by Tal500** [orefalo/svelte-splitpanes#43]
Vercel has a great DX experience with open source, Github, and SvelteKit.

**In addition** to Github Pages deployment of the "master" branch, I think it will be preferable to link this project to Vercel (it should be very very easy, just few clicks).

The reason I think it is needed in addition to Github Pages, is that Vercel can build&preview in parallel all branches, PR and historical commits (per push build). This will give us a preview of the final output, instead of the need to build&test locally.

@orefalo I think you should do it as the maintainer.

Alternative: Use Cloudflare instead. This has better "edge" covering, but has also less good DX experience and features.

**Comment by orefalo** [comment]
Hi @Tal500, you are quite active lately ;-)
I am getting ready to shut down for the Xmas break.

Please provide more details, what do you have in mind? What are you trying to fix?


I used to be on Vercel. Found it too $$$ for my simple use cases.

**Comment by Tal500** [comment]
> Hi @Tal500, you are quite active lately ;-) I am getting ready to shut down for the Xmas break.
> 
> Please provide more details, what do you have in mind? What are you trying to fix?
> 
> I used to be on Vercel. Found it too $$$ for my simple use cases.

Hey, happy vacation! Take your time whenever you wish to implement this.
I'm trying to make Vercel build, together with Github Action, a version of the docs website per commit/PR/branch, so the review process will be safer and easier.

You can see for example that in the SvelteKit official repo, Vercel gives build preview per each what I said, in a similar concept to Github Action: https://github.com/sveltejs/kit/deployments
You can even see the result in the PR pages, next to the github action status. E.g. the status display for a random PR from the SvelteKit official repo: 
![תמונה](https://user-images.githubusercontent.com/1467072/208675639-2c565da2-ec8a-47b2-80e4-f77dd1bdd333.png)

By pressing "details" you can see a live demo of the PR, created by Vercel.

**Comment by Tal500** [comment]
BTW: Don't upgrade the version for every fix/feature commit of mine, I allow you to rest and gather few feature for a week or so :-)

**Comment by orefalo** [comment]
yeah - don't expect much from me in the next two weeks. 
How is you project going?

**Comment by orefalo** [comment]
As far as Vercel, it's trivial.
You can configure the linkage from vercel itself, there is nothing to code. As long as your project follows standards, you are good to go - vercel will detect changes, build and deploy.

**Comment by Tal500** [comment]
> As far as Vercel, it's trivial. You can configure the linkage from vercel itself, there is nothing to code. As long as your project follows standards, you are good to go - vercel will detect changes, build and deploy.

I think only you can link this project to Vercel, since the project is on your account.

**Comment by orefalo** [comment]
that's right.
I am still missing the point - for what benefits?

The actions you built work perfectly, and hosting is 100% free at github.

**Comment by Tal500** [comment]
> that's right. I am still missing the point - for what benefits?
> 
> The actions you built work perfectly, and hosting is 100% free at github.

It just easier to avoid bugs before merging on master, but I get your point.
You may close this issue if you wish

**Comment by orefalo** [comment]
Closing - KISS principle, works great, as is
