### ISSUE TITLE
Error when using with sveltekit 1.0

### ISSUE THREAD

**Issue by jtfogarty** [orefalo/svelte-splitpanes#49]
When I attempt to implement this in +layout.svelte or +page.svelte I get the below error;

<Splitpanes> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules. Otherwise you may need to fix a <Splitpanes>.
Error: <Splitpanes> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules. Otherwise you may need to fix a <Splitpanes>.

**Comment by orefalo** [comment]
Hi @jtfogarty 
Interesting... never saw this error.
Can you submit a sample?

**Comment by jtfogarty** [comment]
Hi @orefalo 
Here is my project
https://github.com/jtfogarty/md-blog-sk
it is on v 0.7.8
Thanks for your quick reply

**Comment by jtfogarty** [comment]
I can get some of the examples on [here](https://orefalo.github.io/svelte-splitpanes/) to work.  
I was looking at the [modern example](https://orefalo.github.io/svelte-splitpanes/examples/styling/splitters-modern) and get an error with 
<HighlightSvelte {code} />
If I remove this the csss gives error.

This example is not one that can be copied / paste.

**Comment by orefalo** [comment]
Happy new year @jtfogarty 

I got your example to work with...

```
<script>
	import { Pane, Splitpanes } from 'svelte-splitpanes';
</script>

<!-- 
{#if Splitpanes}
	<svelte:self this={Splitpanes} />
{/if} -->

<Splitpanes>
	<div>Pane 1</div>
	<div><slot /></div>
</Splitpanes>
```

which brings something we may have missed in the examples/online code... we didn't include the import statement

**Comment by orefalo** [comment]
Just updated all examples with proper import statements - it's obvious to ppl that know svelte, but agreed may be a stretch to beginners.
As far as `<HighlightSvelte {code} />` you should have no issues removing it from your code it you don't import it, reference it in the html.

Please confirm resolution, and close this ticket
Thank you

**Comment by jtfogarty** [comment]
Thanks for the help.
