### ISSUE TITLE
lock or unlock editing of layouts

### ISSUE THREAD

**Issue by vfxturjo** [orefalo/svelte-splitpanes#62]
thank you for the awesome package!

I am making a midi controller app where people will be able to create their own layouts and play. I want to use this package for that. but, only if there were something like "lock layout editing" feature. so, when they play, they will not be able to accidentally mess up their layouts. Please implement a boolean prop for editability of pane. e.g. `editable={false}`

Also, it will be helpful if the event listeners for editability of panes are removed when `editable=false` (less computational load) and when the value is set to true, panes will have their event listeners.

thanks in advance!

**Comment by Tal500** [comment]
You can have this feature already today.
Just set (programically) both `minSize` and `maxSize` to be equal to `size`.

**Comment by vfxturjo** [comment]
thanks for super fast response!

yes i saw in the documentation that a pane can be locked like that. but i think it will make code messy,
for example:

```
<Pane minSize="{editable ? actual_min_size : get_current_size_of_pane}" 
   maxSize="{editable ? actual_max_size : get_current_size_of_pane}">
```
instead of 
```
<Pane minSize="{actual_min_size}" maxSize="{actual_max_size}" {editability}>
```
for all of the panes...

but if you kindly implement this bool, it will be very helpful... and removing the event listeners of the panes will make the app more performant.

**Comment by Tal500** [comment]
> thanks for super fast response!

I'm one of the rare Githubers whom accept the Github mail notifications settings.

> yes i saw in the documentation that a pane can be locked like that. but i think it will make code messy, for example:
> 
> ```
> <Pane minSize="{editable ? actual_min_size : get_current_size_of_pane}" 
>    maxSize="{editable ? actual_max_size : get_current_size_of_pane}">
> ```
> 
> instead of
> 
> ```
> <Pane minSize="{actual_min_size}" maxSize="{actual_max_size}" {editability}>
> ```
> 
> for all of the panes...
> 
> but if you kindly implement this bool, it will be very helpful... and removing the event listeners of the panes will make the app more performant. 

There is a huge improvement you can do that you miss! You can use Svelte data binding instead of notification listening (something I worked on personally very hard) - you have an official demo for this im the demo pages.

So you can use `bind:size={some_variable}` and then your `editable ? ...` stuff with it. Just init the variable `some_variable` to some number 0-100 (other than `null` or `undefined`), and then the code will be clean and automatic.

I kinda want to insist to not create a special property per every possible feature that can be done manually, as long as it not too common but easy to handle.

**Comment by vfxturjo** [comment]
I understand.

Okay then, currently forgetting about the event listeners of the splitpanes, and trying to focus on implementing the UI logic...


Thank you for showing me the way to get size value for each panes. I guess i will somehow store all the sizes into an object because users will dynamically create lots of panes, and save/load layouts. Lets see where i can go


I want to know another thing:
does the panes remove event listeners when min = size = max ?
Or they are still calculated but nothing is changing?

**Comment by Tal500** [comment]
> I understand.
> 
> Okay then, currently forgetting about the event listeners of the splitpanes, and trying to focus on implementing the UI logic...
> 
> Thank you for showing me the way to get size value for each panes. I guess i will somehow store all the sizes into an object because users will dynamically create lots of panes, and save/load layouts. Lets see where i can go
> 
> I want to know another thing: does the panes remove event listeners when min = size = max ? Or they are still calculated but nothing is changing?

I don't remember, so I cannot promise anything. No garentee is promised, but I promise you that the "resize" event will always give the correct sizes of all the panes, so if the panes are "locked" the numbers that would be given(if the event will be fired) would be correct.

**Comment by Tal500** [comment]
@vfxturjo a hint you probably know but I'll say this explicitly:

I didn't want to introduce a new feature here when it's obvious in your case what you should do.

You however implement your own logic in some new wrapper component I.e. `CustomPane` that calls `<Pane>` internally, and controls the min/max size stuff by the trick we had discussed, and expose the custom `editable` prop.

**Comment by vfxturjo** [comment]
> @vfxturjo a hint you probably know but I'll say this explicitly:
> 
> I didn't want to introduce a new feature here when it's obvious in your case what you should do.
> 
> You however implement your own logic in some new wrapper component I.e. `CustomPane` that calls `<Pane>` internally, and controls the min/max size stuff by the trick we had discussed, and expose the custom `editable` prop.

Thanks for reminding!
that will make my life easier ❤
