### ISSUE TITLE
The dblClickSplitter setting has no effect.

### ISSUE THREAD

**Issue by janmadsen1962** [orefalo/svelte-splitpanes#69]
Setting dbClickSplitter = {false} does not prevent pane resizing.
Test for dbClickSplitter missing in function onSplitterDblClick.

**Comment by orefalo** [comment]
That is correct, as per the documentation

dblClickSplitter | boolean | true | Double click on splitter to maximize the next pane
-- | -- | -- | --

on -> dbl click will maximize the pane
off -> default behavior

**Comment by orefalo** [comment]
to achieve the desired outcome you can use

<Pane minSize={20} maxSize={20}>

**Comment by janmadsen1962** [comment]
I would like to disable the splitter dbl click - but still be able to resize panes.

**Comment by orefalo** [comment]
Thank you so much for reporting this issue

It is now fixed.
https://orefalo.github.io/svelte-splitpanes/examples/disable-dbl-click
