### ISSUE TITLE
Set not only the cursor of the splitter

### ISSUE THREAD

**Issue by Tal500** [orefalo/svelte-splitpanes#7]
Continuing PR #6, I think still that something is missing, and Split.js does it better.
Recall last video in #6 (the demo after fix):

https://user-images.githubusercontent.com/1467072/174052584-96ef2a57-d818-44ec-a216-1ecf43b17dd1.mov

You can see that `cursor: col-resize;` or `cursor: row-resize;` is set only to the splitter, meaning it's not showing the cursor on the container at all (when the user escapes the splitter as shown in the video), nor showing the cursor on the whole `document.body` element.

You can see how natural it feels in the [Split.js demo](https://split.js.org/). In the following video, the whole time the user is dragging the splitter:

https://user-images.githubusercontent.com/1467072/174056756-c7583709-ab52-4ebb-a72d-eb1c055a1203.mov

Indeed, you can see in their code they set the cursor not only to the splitter, but also to the container and the body elements ([source](https://github.com/nathancahill/split/blob/f9d7b974d24287864792347edd2c76581f117a22/packages/splitjs/src/split.js#L550-L553)):
```js
// Set the cursor at multiple levels
self.gutter.style.cursor = cursor
self.parent.style.cursor = cursor
document.body.style.cursor = cursor
```

I suggest to do the same in this project.

**Comment by orefalo** [comment]
;-)  - some thank you as the other issues 

will experiment soon

**Comment by orefalo** [comment]
too me some time to understand this one.
now i got it. the point here is that when the user move the pointer beyond the splitter boundaries - the cursor should remain.
good catch

will fix

**Comment by orefalo** [comment]
Fixed - however, I did not implement the fix at the document level
I have the feeling it breaks componentization principles.

If a developer can't sleep at night, b/c the cursor changes outside the boundaries of the split pane, they can always implement the functionality using events.

My call, what do you think?

**Comment by Tal500** [comment]
Seems legit overall
