### ISSUE TITLE
Svelte 4 support

### ISSUE THREAD

**Issue by space-nuko** [orefalo/svelte-splitpanes#70]
Hello, Svelte 4 was recently released. Could this library be updated to support it please? Thank you

https://svelte.dev/blog/svelte-4#migrating

**Comment by Tal500** [comment]
> Hello, Svelte 4 was recently released. Could this library be updated to support it please? Thank you
> 
> https://svelte.dev/blog/svelte-4#migrating

Hi! Do you have any error you see while building with Svelte 4?

**Comment by space-nuko** [comment]
I get a dependency resolution error when installing with `npm` but it's a warning in `pnpm`, according to the announcement you just need to add version 4 to the version constraint for `svelte` (any potentially fix breaking changes but there shouldn't be very many)

**Comment by Tal500** [comment]
> I get a dependency resolution error when installing with `npm` but it's a warning in `pnpm`, according to the announcement you just need to add version 4 to the version constraint for `svelte` (and potentially fix breaking changes but there shouldn't be very many)

I'm busy a little bit and cannot do it in the few days.
Can you please try to modify it the small part by yourself and send a PR? Don't worry about backward compatibility, we have automated tests for it on Svelte 3.

**Comment by orefalo** [comment]
I have it almost complete.

Just having a weird error with linting, which I can't figure...

```
ESLint: 8.41.0

You are linting "node_modules/highlight.js", but all of the files matching the glob pattern "node_modules/highlight.js" are ignored.

If you don't want to lint these files, remove the pattern "node_modules/highlight.js" from the list of arguments passed to ESLint.

If you do want to lint these files, try the following solutions:

* Check your .eslintignore file, or the eslintIgnore property in package.json, to ensure that the files are not configured to be ignored.
* Explicitly list the files from this glob that you'd like to lint on the command-line, rather than providing a glob as an argument.
```


I am planning to release this as 0.8.0

**Comment by wtachau** [comment]
@orefalo would you like any help getting this finished? Would love to support Svelte 4

**Comment by Tal500** [comment]
> @orefalo would you like any help getting this finished? Would love to support Svelte 4

Any PR would be nice🙂

**Comment by orefalo** [comment]
Hi, the linting issue was inherited from a dependency. it is now fixed.
Please test release 0.8.0 and close this ticket as you see fit.
Sincerely,

**Comment by space-nuko** [comment]
Thank you!
