### ISSUE TITLE
Getting "Added non-passive event listener to a scroll-blocking 'touchstart' event." warning in the latest chrome browser

### ISSUE THREAD

**Issue by dhinesh03** [orefalo/svelte-splitpanes#74]
Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

**Comment by orefalo** [comment]
I believe this is what you are refering to

https://stackoverflow.com/questions/37721782/what-are-passive-event-listeners

**Comment by dhinesh03** [comment]
> 

Yes, this is the one.

**Comment by orefalo** [comment]
Looks pretty easy to implement from my quick reading - https://svelte.dev/docs/element-directives#on-eventname

`<div on:touchstart|passive={handleTouchStart}>`

will work on it later today,

Sincerely,

**Comment by dhinesh03** [comment]
> Looks pretty easy to implement from my quick reading - https://svelte.dev/docs/element-directives#on-eventname
> 
> `<div on:touchstart|passive={handleTouchStart}>`
> 
> will work on it later today,
> 
> Sincerely,

Thank you so much

**Comment by orefalo** [comment]
I just released an elegant fix in master.
it should work smoothly
