### ISSUE TITLE
[Feature] dragging at splitter intersection to move the vertical and horizontal splitters at the same time

### ISSUE THREAD

**Issue by ysk3a** [orefalo/svelte-splitpanes#78]
Similar to how vscode handles splitter, when you have 3 or 4 panels (resulting in having an intersection of splitters), it would be a nice enhancement/feature for user to be able to move the splitter at the intersection to move the splitter of both vertical and horizontal direction at the same time.

**Comment by orefalo** [comment]
Thank you - 
Would you have a visual to demonstrate the above capability?

**Comment by orefalo** [comment]
Closing as I see little benefits for this feature.  it's really an edge case.
 
Thank you for using SplitPanes.
