### ISSUE TITLE
Unsafe event binding

### ISSUE THREAD

**Issue by Tal500** [orefalo/svelte-splitpanes#8]
The event binding on the following lines are unsafe:
https://github.com/orefalo/svelte-splitpanes/blob/2fcc1aa99fb923c67d29e870b60a1abc4c4c9b38/src/lib/Splitpanes.svelte#L176-L226

Why? Because the Svelte component might be destroyed while the user start the splitter dragging.

### Solution 1
Add a Boolean variable indicating if the events are bounded or not, and do the following:
```ts
onDestroy(() => {
    if (eventsBounded) {
        unbindEvents();
    }
});
```

### Solution 2
Use [\<svelte:window\>](https://svelte.dev/tutorial/svelte-window). 
Indeed, see the following quote from [Svelte docs](https://svelte.dev/docs#template-syntax-svelte-window):
> The <svelte:window> element allows you to add event listeners to the window object without worrying about removing them when > the component is destroyed, or checking for the existence of window when server-side rendering.
> Unlike <svelte:self>, this element may only appear at the top level of your component and must never be inside a block or element.

It is a simple solution, but I think it fails to detect if `ontouchstart` is an available window event or not, as this lines checks:
https://github.com/orefalo/svelte-splitpanes/blob/2fcc1aa99fb923c67d29e870b60a1abc4c4c9b38/src/lib/Splitpanes.svelte#L181-L184

This also requires redesigning the events handling, to check the current state (e.g. `isReady`).

### Solution 3
Like Solution 2, but better. This is experimental, didn't check it at all.
You might be able to condition `svelte:window` tag based on some JS condition. The result should be:
```svelte
<svelte:window on:... />
{#if browser && ('ontouchstart' in window)}
<svelte:window on:... />
{/if}
```

**Comment by Tal500** [comment]
Thank you for the awesome package!

How I got here:
I've been working since this year about a new website in Svelte, so I see myself need to port some vanilla js libraries that are cool but not SSR nor component friendly, so the website will look cool.
I said to myself after the whole adapting hell(this is why I know all these tiny details) I'll make my own Svelte implementation of split.js someday, and then I saw your new project so I became more optimistic.

I'd like to help this project more if needed.
BTW: I've been working also about a cool dynamic modaling(dialogs) system. Might decouple this system to a formal library and share it one day, when I'll be available.

**Comment by orefalo** [comment]
I know what you are talking about. The svelte ecosystem is still young.

I ported splitpane because I couldn't find one I like.
next I must port a decent treeview component. unfortunately I have higher priorities right now.

A model library? can't wait to see it. the ones I've seen are also quite simple. does it work with tailwind?

Any help is welcome, I'll be happy to share views and add you as a contributor.

I am on discord - use https://discord.gg/MSmFsEph to connect.

**Comment by orefalo** [comment]
ok - Solution 1 is the easiest - there is already a flag, isReady

**Comment by Tal500** [comment]
> ok - Solution 1 is the easiest - there is already a flag, isReady

This solution is fine only if it allowed to call unbind events function twice(possibly by mouse up and by destroying), I want to believe it's OK in JS, need to read MDN and to check the browser developer console.

**Comment by Tal500** [comment]
> > ok - Solution 1 is the easiest - there is already a flag, isReady
> 
> This solution is fine only if it allowed to call unbind events function twice(possibly by mouse up and by destroying), I want to believe it's OK in JS, need to read MDN and to check the browser developer console.

Acoording to what I read in MDN few days ago, it's totally fine to call `removeEventListener` on events that are presently not registered, so although it's tricky, it's fine to call `unbindEvents` many times for the edge cases.
