### ISSUE TITLE
[Feature] Double-click to reset size

### ISSUE THREAD

**Issue by rylydou** [orefalo/svelte-splitpanes#80]
An option should be added to change the behavior of double click to reset a pane to it's original size instead of minimizing.

**Comment by orefalo** [comment]
Hi @rylydou 
With this approach, you would have an option for every single use case and the api would quickly become out of control.

a more elegant approach could be to let developer  implement their own double click behavior.

that's the way it's built.

trap the double click event and program your handler.

**Comment by orefalo** [comment]
closing as resolved
