### ISSUE TITLE
Splitpanes.svelte:284 Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by ndeshpande2022** [orefalo/svelte-splitpanes#90]
After upgrading to v0.8.2 I'm seeing an error in our logs. 

Splitpanes.svelte:284 Unable to preventDefault inside passive event listener invocation.

![image](https://github.com/orefalo/svelte-splitpanes/assets/110494302/14e2ec43-6067-482a-a0c3-5221d952aa05)

Otherwise the update seems to work okay

**Comment by orefalo** [comment]
Hi @ndeshpande2022 ndeshpande2022
That's expected,
That's because the events are now passive by default.

This is used to enable performance optimizations described in [§ 2.8 Observing event listeners](https://dom.spec.whatwg.org/#observing-event-listeners) and touch devices.

**Comment by ndeshpande2022** [comment]
@orefalo - thanks so much for letting me know. I saw the commit, and I just wanted to make sure I wasn't doing something wrong.

Thanks so much!
