### ISSUE TITLE
Store splitter state in localstorage

### ISSUE THREAD

**Issue by reformstudios** [orefalo/svelte-splitpanes#98]
Is it possible to get the state of the splitters so we can store the state between sessions in localstorage?

**Comment by orefalo** [comment]
Hi,
You can get the state of the panes, not the splitter

**Comment by reformstudios** [comment]
So it's not possible to store the splitter position between sessions?

**Comment by orefalo** [comment]
directly, no
indirectly yes - get the pane sizes

**Comment by orefalo** [comment]
closing - the component provides events and APIs to implement this logic in userspace
