### ISSUE TITLE
Set fixed size in px/rem?

### ISSUE THREAD

**Issue by reformstudios** [orefalo/svelte-splitpanes#99]
I noticed that with a splitter that scales to the browser window, my fixed pane was still changing size. How can I fix this to an absolute value rather than a percentage?

**Comment by orefalo** [comment]
Unfortunately we do not support px/rem sizing. It is not trivial.
So for now, you will need to calculate it. Hook the event, figure the pane % based on pixel sizing and set it

If I recall there is a PR for an formal implementaiton, you want to pick it up.
